asurion_piplines:
  outputs:
    prod:
      dbname: phub
      host: psql-uat.asurion.thoughtwire.io
      pass: 'ZjLtqm22Sfxam%92'
      port: 5432
      schema: public
      threads: 10
      type: postgres
      user: phub@vcasurionh4xkhl-uat2-psql


    uat:
      dbname: phub
      host: 10.25.4.6
      pass: '0lRk61%1c4Lb18*Y'
      port: 5432
      schema: public
      threads: 10
      type: postgres
      user: phub@vcasurionsa5744-uat-3-psql

  target: prod
